- name: variables from inventory
  hosts: localhost
  tasks: # list of tasks/collections/modules
  - name: printing variables from inventory
    ansible.builtin.debug:
      msg: "I am learning {{course}} from {{trainer}} and duration is {{duration}}"