- name: conditions
  hosts: web
  become: yes
  tasks: #list of tasks/collections/modules
  - name: using conditions
    ansible.builtin.command: id expense
    register: user_info
    ignore_errors: true

  - name: print user info 
    ansible.builtin.debug:
      msg: "user info is: {{user_info}}"

  - name: if user not exists, create user using when condition
    ansible.builtin.command: useradd expense
    when: user_info.rc != 0

  - name: print info
    ansible.builtin.debug:
      msg: "Hello, end of script"