- name: conditions
  hosts: web
  tasks: #list of tasks/collections/modules
  - name: using conditions
    ansible.builtin.command: id expense
    register: user_info
    ignore_errors: true

  - name: print user info 
    ansible.builtin.debug:
      msg: "user info is: {{user_info}}"
  - name: print info
    ansible.builtin.debug:
      msg: "Hello, end of script"