- name: filters
  hosts: localhost
  tasks: # list of tasks/collections/modules
  - name: default
    ansible.builtin.debug:
      msg: "{{course | default('ansible')}}"

# uppercase
- name: uppercase
  hosts: localhost
  vars:
    greetings: "Hi, Good Morning"
  tasks: #list of tasks/collections/modules
  - name: convert into uppercase
    ansible.builtin.debug:
      msg: "{{greetings|upper}}"

# lowercase
- name: lowercase
  hosts: localhost
  vars:
    greetings: "Hi, Good Morning"
  tasks: # list of tasks/collections/modules
  - name: convert into lowercase
    ansible.builtin.debug:
      msg: "{{greetings|lower}}"

#remove duplicates
- name: remove duplicates
  hosts: localhost
  vars:
    numbers: [1,1,1,2,2,2,4,4,5,5,6,7,7]
  tasks: #list of tasks/collections/modules
  - name: removing duplicates
    ansible.builtin.debug:
      msg: "{{numbers|unique}}"

#print min and max
- name: min and max
  hosts: localhost
  vars:
    ages: [18,25,34,45,55,65,75]
  tasks: #list of tasks/collections/modules
  - name: min age and max age
    ansible.builtin.debug:
      msg: "min age is: {{ages|min}} , max age is: {{ages|max}}" 