- name: installing using loops
  hosts: web
  become: yes
  tasks: # list of tasks/collections/modules
  - name: installing
    ansible.builtin.dnf:
      name: {{item}}
      state: installed
    loop:
    - mysql
    - nginx
    - postfix