[web]
172.31.24.239

[ansiblemaster]
localhost

[db]
172.31.24.240

[backend]
172.31.24.241

[all:children]
web
db
backend

[ansiblemaster:vars]
course="Ansible"
trainer="Avin"
duration="8hrs"
wishes="Morning fron inv"
